import { Link } from "@/i18n/navigation";
import { ActionForm } from "@/components/action-form";
import { expirePaymentsForm, generateStatementForm } from "@/app/actions/money-forms";
import { listPaymentLinks } from "@/db/queries/payments";
import { listStatements } from "@/db/queries/statements";
import { listUsers } from "@/db/queries/users";
import { formatLocalDateTime } from "@/lib/messaging";
import { formatMoney } from "@/lib/money";
import { periodLabel } from "@/lib/statement-html";
import { requireAdminPage } from "@/lib/page-guards";

/**
 * Payment links (#8) and owner statements (#3) — plan §5.O11.
 *
 * A payment link is a record, not an integration: v1 stores the provider's URL
 * and its status, and a human marks it paid (plan §1.5). Statements are
 * generated by `npm run statements`; this page runs the same generator for one
 * owner and period, idempotently.
 */
export default async function AdminMoneyPage() {
  await requireAdminPage();
  const [links, statements, users] = await Promise.all([
    listPaymentLinks(),
    listStatements(),
    listUsers(),
  ]);
  const owners = users.filter((user) => user.ownerId);
  const period = new Date().toISOString().slice(0, 7);

  return (
    <section className="space-y-8">
      <h1 className="text-2xl font-semibold">Cobros y liquidaciones</h1>

      <section className="space-y-2">
        <h2 className="font-medium">Links de pago ({links.length})</h2>
        <p className="text-xs text-neutral-500">
          Se crean y se marcan pagados desde la reserva. Acá está la vista de conjunto.
        </p>
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="border-b text-left">
              <th className="py-1">Reserva</th>
              <th>Proveedor</th>
              <th>Monto</th>
              <th>Estado</th>
              <th>Vence</th>
            </tr>
          </thead>
          <tbody>
            {links.map(({ paymentLink, bookingReference, listingTitle }) => (
              <tr key={paymentLink.id} className="border-b">
                <td className="py-1">
                  <Link
                    href={`/admin/reservas/${paymentLink.bookingId}`}
                    className="text-blue-700 underline"
                  >
                    {bookingReference}
                  </Link>
                  <span className="block text-xs text-neutral-500">{listingTitle}</span>
                </td>
                <td>{paymentLink.provider}</td>
                <td>{formatMoney(paymentLink.amount, paymentLink.currency)}</td>
                <td>{paymentLink.status}</td>
                <td>
                  {paymentLink.expiresAt ? formatLocalDateTime(paymentLink.expiresAt) : "—"}
                </td>
              </tr>
            ))}
            {links.length === 0 && (
              <tr>
                <td colSpan={5} className="py-1 text-neutral-500">
                  Sin links de pago cargados.
                </td>
              </tr>
            )}
          </tbody>
        </table>
        <ActionForm
          action={expirePaymentsForm}
          submitLabel="Vencer los links pasados de fecha"
          className="inline"
          submitClassName="rounded border border-neutral-400 px-3 py-1 text-sm disabled:opacity-50"
        />
      </section>

      <section className="space-y-2">
        <h2 className="font-medium">Liquidaciones ({statements.length})</h2>
        <table className="w-full border-collapse text-sm">
          <thead>
            <tr className="border-b text-left">
              <th className="py-1">Propietario</th>
              <th>Período</th>
              <th>Bruto</th>
              <th>Comisión</th>
              <th>Gastos</th>
              <th>Neto</th>
              <th />
            </tr>
          </thead>
          <tbody>
            {statements.map(({ statement, ownerName }) => (
              <tr key={statement.id} className="border-b">
                <td className="py-1">{ownerName}</td>
                <td>{periodLabel(statement.period)}</td>
                <td>{formatMoney(statement.grossTotal, statement.currency)}</td>
                <td>{formatMoney(statement.commissionTotal, statement.currency)}</td>
                <td>{formatMoney(statement.expensesTotal, statement.currency)}</td>
                <td>
                  <strong>{formatMoney(statement.netTotal, statement.currency)}</strong>
                </td>
                <td>
                  <a href={`/api/estados/${statement.id}.html`} className="text-blue-700 underline">
                    ver
                  </a>
                </td>
              </tr>
            ))}
            {statements.length === 0 && (
              <tr>
                <td colSpan={7} className="py-1 text-neutral-500">
                  Todavía no se generó ninguna liquidación.
                </td>
              </tr>
            )}
          </tbody>
        </table>

        <ActionForm action={generateStatementForm} submitLabel="Generar liquidación">
          <div className="grid grid-cols-2 gap-2 text-sm">
            <label className="space-y-1">
              <span>Propietario</span>
              <select
                name="ownerId"
                required
                className="w-full rounded border border-neutral-300 px-2 py-1"
              >
                {owners.map((owner) => (
                  <option key={owner.ownerId!} value={owner.ownerId!}>
                    {owner.name}
                  </option>
                ))}
              </select>
            </label>
            <label className="space-y-1">
              <span>Período (YYYY-MM)</span>
              <input
                name="period"
                required
                defaultValue={period}
                className="w-full rounded border border-neutral-300 px-2 py-1"
              />
            </label>
          </div>
          <p className="text-xs text-neutral-500">
            Volver a generar el mismo período da el mismo resultado: bruto − comisión −
            gastos = neto, sobre las reservas terminadas de ese mes.
          </p>
        </ActionForm>
      </section>
    </section>
  );
}
